spring.application.name=servicedesk
spring.datasource.url=jdbc:postgresql://localhost:5432/servicedesk
spring.datasource.username=servicedesk
spring.datasource.password=servicedesk
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8081
# OpenAPI Configuration
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=true
#springdoc.packages-to-scan=com.servicedesk.controller
#springdoc.paths-to-match=/api/**
## Customize Swagger UI
#springdoc.swagger-ui.tagsSorter=alpha
#springdoc.swagger-ui.operationsSorter=alpha
#springdoc.swagger-ui.doc-expansion=none
#springdoc.swagger-ui.filter=true
#ddl-auto=validate means Hibernate won?t auto-create tables, it just checks against Flyway migrations. Flyway is the source of truth.
